name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.15.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: go vet
        run: go vet ./...
      - name: go test
        run: go test -v ./...
